INSERT INTO LABORATORIO (NOME) VALUES ('LabTech Alpha');
INSERT INTO LABORATORIO (NOME) VALUES ('BioGenix');
INSERT INTO LABORATORIO (NOME) VALUES ('NanoCore Labs');
INSERT INTO LABORATORIO (NOME) VALUES ('Quantum BioLab');
INSERT INTO LABORATORIO (NOME) VALUES ('Helix Research Center');
INSERT INTO LABORATORIO (NOME) VALUES ('GenomaX');
INSERT INTO LABORATORIO (NOME) VALUES ('Artemis BioSolutions');
INSERT INTO LABORATORIO (NOME) VALUES ('NeuroLab Prime');
INSERT INTO LABORATORIO (NOME) VALUES ('EcoSynth Labs');
INSERT INTO LABORATORIO (NOME) VALUES ('Photon Research Institute');
INSERT INTO LABORATORIO (NOME) VALUES ('ZetaLife Research');
INSERT INTO LABORATORIO (NOME) VALUES ('Solaris Molecular Lab');
INSERT INTO LABORATORIO (NOME) VALUES ('CryoNova Laboratories');
INSERT INTO LABORATORIO (NOME) VALUES ('AstroBiotec');
INSERT INTO LABORATORIO (NOME) VALUES ('InovaGene Lab');
INSERT INTO LABORATORIO (NOME) VALUES ('NovaHelix Research');
INSERT INTO LABORATORIO (NOME) VALUES ('BioArk Technologies');
INSERT INTO LABORATORIO (NOME) VALUES ('Synthex Labs');
INSERT INTO LABORATORIO (NOME) VALUES ('CuraCell Institute');
INSERT INTO LABORATORIO (NOME) VALUES ('DeepMind Genetics');
INSERT INTO LABORATORIO (NOME) VALUES ('PlasmaCore Labs');
INSERT INTO LABORATORIO (NOME) VALUES ('MindForge BioTech');
INSERT INTO LABORATORIO (NOME) VALUES ('Verdant Labs');
INSERT INTO LABORATORIO (NOME) VALUES ('Alkemy Research Co.');
INSERT INTO LABORATORIO (NOME) VALUES ('Prime Helix Labs');
INSERT INTO LABORATORIO (NOME) VALUES ('Bioma Discovery Center');
INSERT INTO LABORATORIO (NOME) VALUES ('Orion Bioworks');
INSERT INTO LABORATORIO (NOME) VALUES ('Zenith Genetic Labs');
INSERT INTO LABORATORIO (NOME) VALUES ('TheraNova Labs');
INSERT INTO LABORATORIO (NOME) VALUES ('GeneWorks Lab');
INSERT INTO LABORATORIO (NOME) VALUES ('Metrix Research Lab');
INSERT INTO LABORATORIO (NOME) VALUES ('Axion Biotech');
INSERT INTO LABORATORIO (NOME) VALUES ('NextPhase Labs');
INSERT INTO LABORATORIO (NOME) VALUES ('OmniGene Research');
INSERT INTO LABORATORIO (NOME) VALUES ('Aeon Cell Science');
INSERT INTO LABORATORIO (NOME) VALUES ('NeuraSyn Labs');
INSERT INTO LABORATORIO (NOME) VALUES ('EcoPulse Laboratories');
INSERT INTO LABORATORIO (NOME) VALUES ('ChronoLabs');
INSERT INTO LABORATORIO (NOME) VALUES ('QuantumSyn Research');
INSERT INTO LABORATORIO (NOME) VALUES ('LumenGene Institute');
INSERT INTO LABORATORIO (NOME) VALUES ('Galactia BioLab');
INSERT INTO LABORATORIO (NOME) VALUES ('Plexus Research');
INSERT INTO LABORATORIO (NOME) VALUES ('EverCell Laboratories');
INSERT INTO LABORATORIO (NOME) VALUES ('Vivaterra Labs');
INSERT INTO LABORATORIO (NOME) VALUES ('NeuroArk Institute');
INSERT INTO LABORATORIO (NOME) VALUES ('Stellar Biogenics');
INSERT INTO LABORATORIO (NOME) VALUES ('CelulaOne Labs');
INSERT INTO LABORATORIO (NOME) VALUES ('MiraGene Technologies');
INSERT INTO LABORATORIO (NOME) VALUES ('Vitalis Research Hub');
INSERT INTO LABORATORIO (NOME) VALUES ('Hyperion Molecular Lab');

INSERT INTO PROPRIEDADE (NOME) VALUES ('Fazenda Horizonte Azul');
INSERT INTO PROPRIEDADE (NOME) VALUES ('Estância Vale Verdejante');
INSERT INTO PROPRIEDADE (NOME) VALUES ('Sítio Três Cedros');
INSERT INTO PROPRIEDADE (NOME) VALUES ('Chácara Lua Serena');
INSERT INTO PROPRIEDADE (NOME) VALUES ('Fazenda Morro Encantado');
INSERT INTO PROPRIEDADE (NOME) VALUES ('Refúgio da Serra Dourada');
INSERT INTO PROPRIEDADE (NOME) VALUES ('Fazenda Águas Claras');
INSERT INTO PROPRIEDADE (NOME) VALUES ('Rancho do Sol Poente');
INSERT INTO PROPRIEDADE (NOME) VALUES ('Sítio Esperança Nova');
INSERT INTO PROPRIEDADE (NOME) VALUES ('Fazenda Caminho das Pedras');
INSERT INTO PROPRIEDADE (NOME) VALUES ('Estância Tranquila');
INSERT INTO PROPRIEDADE (NOME) VALUES ('Fazenda Lago Cristalino');
INSERT INTO PROPRIEDADE (NOME) VALUES ('Fazenda Dois Riachos');
INSERT INTO PROPRIEDADE (NOME) VALUES ('Chácara Estrela do Norte');
INSERT INTO PROPRIEDADE (NOME) VALUES ('Fazenda Boa Ventura');
INSERT INTO PROPRIEDADE (NOME) VALUES ('Sítio Pedra Branca');
INSERT INTO PROPRIEDADE (NOME) VALUES ('Fazenda do Céu Anil');
INSERT INTO PROPRIEDADE (NOME) VALUES ('Vale dos Ventos');
INSERT INTO PROPRIEDADE (NOME) VALUES ('Estância Monte Verde');
INSERT INTO PROPRIEDADE (NOME) VALUES ('Fazenda Jardim das Oliveiras');
INSERT INTO PROPRIEDADE (NOME) VALUES ('Sítio Bela Aurora');
INSERT INTO PROPRIEDADE (NOME) VALUES ('Chácara Pôr do Sol');
INSERT INTO PROPRIEDADE (NOME) VALUES ('Fazenda Luar do Campo');
INSERT INTO PROPRIEDADE (NOME) VALUES ('Rancho Horizonte Vivo');
INSERT INTO PROPRIEDADE (NOME) VALUES ('Fazenda Santa Felicidade');
INSERT INTO PROPRIEDADE (NOME) VALUES ('Sítio Coração de Terra');
INSERT INTO PROPRIEDADE (NOME) VALUES ('Fazenda Morada do Vale');
INSERT INTO PROPRIEDADE (NOME) VALUES ('Refúgio da Lua Nova');
INSERT INTO PROPRIEDADE (NOME) VALUES ('Fazenda Riacho Doce');
INSERT INTO PROPRIEDADE (NOME) VALUES ('Estância Vento Sul');
INSERT INTO PROPRIEDADE (NOME) VALUES ('Fazenda Encanto das Flores');
INSERT INTO PROPRIEDADE (NOME) VALUES ('Chácara Raiz do Campo');
INSERT INTO PROPRIEDADE (NOME) VALUES ('Sítio Horizonte Livre');
INSERT INTO PROPRIEDADE (NOME) VALUES ('Fazenda Terra Alta');
INSERT INTO PROPRIEDADE (NOME) VALUES ('Estância Água Serena');
INSERT INTO PROPRIEDADE (NOME) VALUES ('Fazenda do Vale Dourado');
INSERT INTO PROPRIEDADE (NOME) VALUES ('Chácara Três Corações');
INSERT INTO PROPRIEDADE (NOME) VALUES ('Fazenda São Cristóvão');
INSERT INTO PROPRIEDADE (NOME) VALUES ('Sítio Nova Esperança');
INSERT INTO PROPRIEDADE (NOME) VALUES ('Rancho Pedra do Sol');
INSERT INTO PROPRIEDADE (NOME) VALUES ('Fazenda Céu de Estrelas');
INSERT INTO PROPRIEDADE (NOME) VALUES ('Estância Caminho Verde');
INSERT INTO PROPRIEDADE (NOME) VALUES ('Fazenda Encanto do Oeste');
INSERT INTO PROPRIEDADE (NOME) VALUES ('Chácara Pingo de Ouro');
INSERT INTO PROPRIEDADE (NOME) VALUES ('Fazenda Vale do Silêncio');
INSERT INTO PROPRIEDADE (NOME) VALUES ('Sítio Rosa dos Ventos');
INSERT INTO PROPRIEDADE (NOME) VALUES ('Fazenda dos Ipês');
INSERT INTO PROPRIEDADE (NOME) VALUES ('Estância Boa Esperança');
INSERT INTO PROPRIEDADE (NOME) VALUES ('Fazenda Brilho do Amanhecer');

INSERT INTO PESSOA (NOME, DATA_INICIAL, DATA_FINAL, OBSERVACOES, LABORATORIO_ID, PROPRIEDADE_ID)
VALUES ('Ariadne Luz', '2025-01-10 08:00:00', '2025-02-10 17:00:00', 'Responsável pela coleta de amostras minerais.', 3, 12);

INSERT INTO PESSOA (NOME, DATA_INICIAL, DATA_FINAL, OBSERVACOES, LABORATORIO_ID, PROPRIEDADE_ID)
VALUES ('Caio Montanha', '2025-03-01 09:30:00', '2025-03-15 16:45:00', 'Realizou inspeções no solo de pastagens.', 7, 4);

INSERT INTO PESSOA (NOME, DATA_INICIAL, DATA_FINAL, OBSERVACOES, LABORATORIO_ID, PROPRIEDADE_ID)
VALUES ('Helena das Veredas', '2025-02-12 10:00:00', '2025-02-28 15:00:00', 'Observações sobre o impacto de agrotóxicos.', 14, 29);

INSERT INTO PESSOA (NOME, DATA_INICIAL, DATA_FINAL, OBSERVACOES, LABORATORIO_ID, PROPRIEDADE_ID)
VALUES ('Theo Amaral', '2025-01-05 07:30:00', '2025-01-25 17:30:00', 'Teste de resistência do feijão da estação.', 1, 6);

INSERT INTO PESSOA (NOME, DATA_INICIAL, DATA_FINAL, OBSERVACOES, LABORATORIO_ID, PROPRIEDADE_ID)
VALUES ('Irene Sol', '2025-04-01 08:00:00', '2025-04-20 17:00:00', 'Análise de flora local.', 9, 11);

INSERT INTO PESSOA (NOME, DATA_INICIAL, DATA_FINAL, OBSERVACOES, LABORATORIO_ID, PROPRIEDADE_ID)
VALUES ('Mateus Lago', '2025-02-01 09:00:00', '2025-03-01 17:00:00', 'Estudo de fontes hídricas.', 4, 20);

INSERT INTO PESSOA (NOME, DATA_INICIAL, DATA_FINAL, OBSERVACOES, LABORATORIO_ID, PROPRIEDADE_ID)
VALUES ('Camila Prado', '2025-03-10 10:00:00', '2025-04-10 16:30:00', 'Supervisão da coleta de dados climáticos.', 12, 7);

INSERT INTO PESSOA (NOME, DATA_INICIAL, DATA_FINAL, OBSERVACOES, LABORATORIO_ID, PROPRIEDADE_ID)
VALUES ('Rafael Vale', '2025-02-15 08:00:00', '2025-02-28 18:00:00', 'Monitoramento de pragas naturais.', 8, 9);

INSERT INTO PESSOA (NOME, DATA_INICIAL, DATA_FINAL, OBSERVACOES, LABORATORIO_ID, PROPRIEDADE_ID)
VALUES ('Viviane Campos', '2025-01-20 07:00:00', '2025-02-10 17:00:00', 'Estudo da biodiversidade em áreas degradadas.', 5, 17);

INSERT INTO PESSOA (NOME, DATA_INICIAL, DATA_FINAL, OBSERVACOES, LABORATORIO_ID, PROPRIEDADE_ID)
VALUES ('Léo Marfim', '2025-03-01 09:00:00', '2025-03-20 15:00:00', 'Coleta de amostras foliares para análise genética.', 16, 8);

INSERT INTO PESSOA (NOME, DATA_INICIAL, DATA_FINAL, OBSERVACOES, LABORATORIO_ID, PROPRIEDADE_ID)
VALUES ('Diana Monte', '2025-01-03 08:00:00', '2025-01-20 17:00:00', 'Registro de aves nativas no entorno.', 10, 5);

INSERT INTO PESSOA (NOME, DATA_INICIAL, DATA_FINAL, OBSERVACOES, LABORATORIO_ID, PROPRIEDADE_ID)
VALUES ('Jonas Rio', '2025-03-05 08:30:00', '2025-03-22 17:30:00', 'Análise de sedimentos.', 11, 14);

INSERT INTO PESSOA (NOME, DATA_INICIAL, DATA_FINAL, OBSERVACOES, LABORATORIO_ID, PROPRIEDADE_ID)
VALUES ('Luísa Neblina', '2025-01-17 10:00:00', '2025-02-14 16:00:00', 'Pesquisa sobre fungos em áreas úmidas.', 19, 24);

INSERT INTO PESSOA (NOME, DATA_INICIAL, DATA_FINAL, OBSERVACOES, LABORATORIO_ID, PROPRIEDADE_ID)
VALUES ('Pedro Cedro', '2025-03-15 09:30:00', '2025-04-05 15:30:00', 'Identificação de novas variedades nativas.', 13, 13);

INSERT INTO PESSOA (NOME, DATA_INICIAL, DATA_FINAL, OBSERVACOES, LABORATORIO_ID, PROPRIEDADE_ID)
VALUES ('Sara Nogueira', '2025-02-03 07:45:00', '2025-03-01 17:45:00', 'Experimentos com controle biológico.', 21, 30);

INSERT INTO PESSOA (NOME, DATA_INICIAL, DATA_FINAL, OBSERVACOES, LABORATORIO_ID, PROPRIEDADE_ID)
VALUES ('Artur das Águas', '2025-01-12 08:00:00', '2025-01-30 18:00:00', 'Avaliação da qualidade da água.', 6, 10);

INSERT INTO PESSOA (NOME, DATA_INICIAL, DATA_FINAL, OBSERVACOES, LABORATORIO_ID, PROPRIEDADE_ID)
VALUES ('Júlia Aurora', '2025-03-08 09:00:00', '2025-04-01 17:00:00', 'Pesquisadora visitante em culturas tropicais.', 23, 2);

INSERT INTO PESSOA (NOME, DATA_INICIAL, DATA_FINAL, OBSERVACOES, LABORATORIO_ID, PROPRIEDADE_ID)
VALUES ('Daniel Carvalho', '2025-02-10 08:15:00', '2025-02-25 16:15:00', 'Estudos em irrigação eficiente.', 2, 1);

INSERT INTO PESSOA (NOME, DATA_INICIAL, DATA_FINAL, OBSERVACOES, LABORATORIO_ID, PROPRIEDADE_ID)
VALUES ('Flora Campos', '2025-01-28 10:00:00', '2025-02-18 14:00:00', 'Observação de ciclo de plantio em áreas semiáridas.', 20, 18);